name: Build Github Pages
run-name: Build Github Pages using registry branch ${{ inputs.registry_branch }} by @${{ github.actor }}

on:
  push:
    branches:
      - snapshot

  workflow_call:
    inputs:
      registry_branch:
        description: 'Branch name to checkout the registry from.'
        required: true
        type: string
        default: 'snapshot'

  workflow_dispatch:
    inputs:
      registry_branch:
        description: 'Branch name to checkout the registry from.'
        required: true
        type: string
        default: 'snapshot'

jobs:
  build_github_pages:
    name: Directory Listings Index
    permissions:
      contents: read  # Recommended checkout permissions.

    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.registry_branch }}

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: release  # Directory to generate index.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'release'  # Upload generated folder.

  deploy_github_pages:
    name: Deploy Github Pages
    needs: build_github_pages

    permissions:
      pages: write     # To deploy to Pages.
      id-token: write  # To verify the deployment originates from an appropriate source.

    # Deploy to the github-pages environment.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: self-hosted
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

